# Generated by Django 4.2.7 on 2023-11-14 01:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='survey',
            old_name='ansl',
            new_name='ans1',
        ),
    ]
